import { BLANK_A4_PDF } from '@pdfme/common';

export const template = {
  schemas: [
    [
      {
        name: 'image1',
        type: 'image',
        content: '',
        position: {
          x: 10.74,
          y: 20,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image2',
        type: 'image',
        content: '',
        position: {
          x: 48.32,
          y: 20,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image3',
        type: 'image',
        content: '',
        position: {
          x: 86.3,
          y: 20,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image4',
        type: 'image',
        content: '',
        position: {
          x: 124.08,
          y: 20,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image5',
        type: 'image',
        content: '',
        position: {
          x: 161.68,
          y: 20.26,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image6',
        type: 'image',
        content: '',
        position: {
          x: 10.69,
          y: 58.78,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image7',
        type: 'image',
        content: '',
        position: {
          x: 48.27,
          y: 58.78,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image8',
        type: 'image',
        content: '',
        position: {
          x: 86.25,
          y: 58.78,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image9',
        type: 'image',
        content: '',
        position: {
          x: 124.03,
          y: 58.78,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image10',
        type: 'image',
        content: '',
        position: {
          x: 161.63,
          y: 59.04,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image11',
        type: 'image',
        content: '',
        position: {
          x: 10.63,
          y: 97.36,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image12',
        type: 'image',
        content: '',
        position: {
          x: 48.21,
          y: 97.36,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image13',
        type: 'image',
        content: '',
        position: {
          x: 86.19,
          y: 97.36,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image14',
        type: 'image',
        content: '',
        position: {
          x: 123.97,
          y: 97.36,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image15',
        type: 'image',
        content: '',
        position: {
          x: 161.68,
          y: 97.36,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image16',
        type: 'image',
        content: '',
        position: {
          x: 10.58,
          y: 135.94,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image17',
        type: 'image',
        content: '',
        position: {
          x: 48.16,
          y: 135.94,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image18',
        type: 'image',
        content: '',
        position: {
          x: 86.14,
          y: 135.94,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image19',
        type: 'image',
        content: '',
        position: {
          x: 123.92,
          y: 135.94,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image20',
        type: 'image',
        content: '',
        position: {
          x: 161.63,
          y: 135.94,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image21',
        type: 'image',
        content: '',
        position: {
          x: 10.53,
          y: 174.52,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image22',
        type: 'image',
        content: '',
        position: {
          x: 48.11,
          y: 174.52,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image23',
        type: 'image',
        content: '',
        position: {
          x: 86.09,
          y: 174.52,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image24',
        type: 'image',
        content: '',
        position: {
          x: 123.87,
          y: 174.52,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image25',
        type: 'image',
        content: '',
        position: {
          x: 161.58,
          y: 174.52,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image26',
        type: 'image',
        content: '',
        position: {
          x: 10.74,
          y: 213.1,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image27',
        type: 'image',
        content: '',
        position: {
          x: 48.32,
          y: 213.1,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image28',
        type: 'image',
        content: '',
        position: {
          x: 86.3,
          y: 213.1,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image29',
        type: 'image',
        content: '',
        position: {
          x: 124.08,
          y: 213.1,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
      {
        name: 'image30',
        type: 'image',
        content: '',
        position: {
          x: 161.79,
          y: 213.1,
        },
        width: 36,
        height: 36,
        rotate: 0,
        opacity: 1,
        required: false,
      },
    ],
  ],
  basePdf: BLANK_A4_PDF,
  pdfmeVersion: '5.3.15',
};
